;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "clj-kondo-skill")
(def path ".")
(def version "0.2.4")
(def tag "0.2.4")
(def generated-at "2020-11-17T07:13:19Z")
