;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "clj-kondo-skill")
(def path ".")
(def version "0.2.6")
(def tag "0.2.6")
(def generated-at "2020-11-19T00:39:32Z")
